### ISSUE TITLE
Missing Rails helper in features test

### ISSUE THREAD

**Issue by dowpm** [learn-co-curriculum/routing-nested-resources-lab#10]

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
