### ISSUE TITLE
Recommendation: Complete the Modifying Nested Resources Read Me Lesson First

### ISSUE THREAD

**Issue by Marie-Burns22** [learn-co-curriculum/routing-nested-resources-lab#11]
The next lesson (Modifying Nested Routes) explains how/why to set up some of the conditionals needed to pass several tests.  I would recommend going through that before attempting this lab.

**Comment by drakeltheryuujin** [comment]
We have updated the materials for V8 of this curriculum and believe this issue has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
