### ISSUE TITLE
Please update the artists/show.html.erb solution so it's not confusing students

### ISSUE THREAD

**Issue by milos381** [learn-co-curriculum/routing-nested-resources-lab#19]
There should be a different solution for the artists/show.html.erb page.

This way, `link_to song.title, artist_song_path(@artist, song)` , would give us two different paths to a view content, depending if we are coming from artists or songs database.

This way `link_to song.title, song_path(song)` we would have the same relative path to a content, regardless of where are we coming from.

PS. The test would fail this way, but at least you should write the students why there are two different paths to the same content, so it's not confusing...

**Comment by bal360** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
