### ISSUE TITLE
Missing Rails helper required

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/routing-nested-resources-lab#6]
I don't know if this was intentional or not, but the specs artists_spec and songs_spec are both missing ```require 'rails_helper'```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
