### ISSUE TITLE
Views/Artists/Show Solution does not include the updated link 

### ISSUE THREAD

**Issue by byojelly** [learn-co-curriculum/routing-nested-resources-lab#7]
The solution for this lab does not include the necessary code for the link to the artist_song_path which is required to pass the lab

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
