### ISSUE TITLE
Colors missing on many of the tests in Rails section lab

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/routing-nested-resources-lab#8]
It's tough to tell which tests you've passed when they are all in white type, not green for passing and red for failing.

One solution is to create .rspec file in the lab directory and put this in it:
--color
--format documentation
--require spec_helper

Thank you.

**Comment by drakeltheryuujin** [comment]
I believe this [commit](https://github.com/learn-co-curriculum/routing-nested-resources-lab/commit/45958c11ad08b0c464a9e0ee4a245d7ac7f055d5) has resolved this issue as it appears to be giving the red/green readouts.

Thanks for your feedback!
